name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
    - name: Log node version
      run: node -v
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-versio: 6
      run: node -v
         